// Sampled-audio bank (VFX_ASSETS WS-F1). Optional enhancement over the
// procedural synth in `audio.ts`: it fetches + decodes small original WAV beds
// and one-shot SFX (generated by scripts/assets/generate_audio.mjs) into
// AudioBuffers, layered on top of the synth on medium+ tiers.
//
// Boot floor (§1): everything is best-effort. With no `fetch`/AudioContext
// (headless), a missing file, or a decode failure, every getter returns null
// and the synth stays the guaranteed sound. No asset is `import`ed — URLs are
// plain runtime strings under /assets/audio, keeping the no-asset-import guard
// (audio test 21) green.

export const SAMPLED_AUDIO_BASE = '/assets/audio';
const AUDIO_EXT = '.wav';

/** Biomes that ship a generated ambient bed (must match generate_audio.mjs). */
export const MUSIC_BEDS = ['grass', 'forest', 'snow', 'desert', 'wasteland', 'coast'] as const;
export type MusicBed = (typeof MUSIC_BEDS)[number];

/** High-impact one-shots that ship a generated sample. */
export const SFX_KEYS = ['crit', 'impact-heavy', 'fanfare', 'whoosh'] as const;
export type SfxKey = (typeof SFX_KEYS)[number];

const hasFetch = typeof fetch !== 'undefined';

function musicUrl(bed: MusicBed): string {
  return `${SAMPLED_AUDIO_BASE}/music/${bed}${AUDIO_EXT}`;
}
function sfxUrl(key: SfxKey): string {
  return `${SAMPLED_AUDIO_BASE}/sfx/${key}${AUDIO_EXT}`;
}

/**
 * Decodes + caches sampled audio for one AudioContext. Construction never
 * touches the network; callers `prefetch` what a tier wants and read buffers
 * synchronously once they resolve (null until then, so the synth covers the gap).
 */
export class SampledAudioBank {
  private buffers = new Map<string, AudioBuffer | null>();
  private pending = new Map<string, Promise<AudioBuffer | null>>();

  constructor(private ctx: BaseAudioContext) {}

  /** Kick off decoding the common SFX + a biome bed; safe to call repeatedly. */
  prefetch(bed?: MusicBed): void {
    for (const key of SFX_KEYS) void this.load(sfxUrl(key));
    if (bed) void this.load(musicUrl(bed));
  }

  /** Decoded SFX buffer, or null until it resolves / on any failure. */
  sfx(key: SfxKey): AudioBuffer | null {
    const url = sfxUrl(key);
    void this.load(url);
    return this.buffers.get(url) ?? null;
  }

  /** Decoded ambient bed for a biome, or null until it resolves / on any failure. */
  music(bed: string): AudioBuffer | null {
    if (!(MUSIC_BEDS as readonly string[]).includes(bed)) return null;
    const url = musicUrl(bed as MusicBed);
    void this.load(url);
    return this.buffers.get(url) ?? null;
  }

  private load(url: string): Promise<AudioBuffer | null> {
    if (this.buffers.has(url)) return Promise.resolve(this.buffers.get(url) ?? null);
    const existing = this.pending.get(url);
    if (existing) return existing;
    if (!hasFetch || typeof this.ctx.decodeAudioData !== 'function') {
      this.buffers.set(url, null);
      return Promise.resolve(null);
    }
    const p = fetch(url)
      .then((res) => (res.ok ? res.arrayBuffer() : Promise.reject(new Error(`status ${res.status}`))))
      .then((bytes) => this.ctx.decodeAudioData(bytes))
      .then((buf) => {
        this.buffers.set(url, buf);
        this.pending.delete(url);
        return buf;
      })
      .catch(() => {
        this.buffers.set(url, null); // remember the miss so the synth owns it
        this.pending.delete(url);
        return null;
      });
    this.pending.set(url, p);
    return p;
  }
}
